### ISSUE TITLE
Support passing the country

### ISSUE THREAD

**Issue by D-stefaang** [wxnnvs/UberEatsScraper#1]
You could use [argparse](https://docs.python.org/3/library/argparse.html) to scan a single country / city.

```
python main.py --country be --city ghent
```

**Comment by wxnnvs** [comment]
fixed [here](https://github.com/wxnnvs/UberEatsScraper/commit/e019dfe5a891383139a1b62b13bff668d34f73c8), [here](https://github.com/wxnnvs/UberEatsScraper/commit/48e786b664ae08d95adc27bf62dfc87dbbdaee66) and [here](https://github.com/wxnnvs/UberEatsScraper/commit/e8c5f3d5f1ba9757b8ebc25181b1cc18afb6fda1)
[release](https://github.com/wxnnvs/UberEatsScraper/releases/tag/v1.4)
usage: `python main.py -c be` or `python main.py -c be fr de`

**Comment by wxnnvs** [comment]
I will add city specific scraping later on
